---
# Clock is now published by dedicated clock_bridge in pfms launch file
# Removed to prevent multiple clock publishers
# - ros_topic_name: "/orange/imu"
#   gz_topic_name: "/orange_audibot/imu"
#   ros_type_name: "sensor_msgs/msg/Imu"
#   gz_type_name: "gz.msgs.IMU"
#   direction: GZ_TO_ROS
- ros_topic_name: "/orange/odom"
  gz_topic_name: "/model/orange_audibot/odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS
- ros_topic_name: "/orange/steering_cmd"
  gz_topic_name: "/model/orange_audibot/steering_cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/orange/brake_cmd"
  gz_topic_name: "/model/orange_audibot/brake_cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/orange/throttle_cmd"
  gz_topic_name: "/model/orange_audibot/throttle_cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/orange/speed_cmd"
  gz_topic_name: "/model/orange_audibot/speed_cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/orange/gear_cmd"
  gz_topic_name: "/model/orange_audibot/gear_cmd"
  ros_type_name: "std_msgs/msg/UInt32"
  gz_type_name: "gz.msgs.UInt32"
  direction: ROS_TO_GZ
- ros_topic_name: "/orange/joint_states"
  gz_topic_name: "/model/orange_audibot/joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS
- ros_topic_name: "/orange/laserscan"
  gz_topic_name: "/model/orange_audibot/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS
- ros_topic_name: "/orange/sonar"
  gz_topic_name: "/model/orange_audibot/sonar"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS
# - ros_topic_name: "/orange/fix"
#   gz_topic_name: "/orange_audibot/navsat"
#   ros_type_name: "sensor_msgs/msg/NavSatFix"
#   gz_type_name: "gz.msgs.NavSat"
#   direction: GZ_TO_ROS
# - ros_topic_name: "/orange/gnss_heading"
#   gz_topic_name: "/model/orange_audibot/gnss_heading"
#   ros_type_name: "std_msgs/msg/Float64"
#   gz_type_name: "gz.msgs.Double"
#   direction: GZ_TO_ROS
- ros_topic_name: "/orange/camera/image_raw"
  gz_topic_name: "/orange_audibot/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
- ros_topic_name: "/orange/camera/camera_info"
  gz_topic_name: "/orange_audibot/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS
