- topic: /clock
  type: rosgraph_msgs/msg/Clock
  direction: both
- topic: /tf
  type: tf2_msgs/msg/TFMessage
  direction: both
- topic: /tf_static
  type: tf2_msgs/msg/TFMessage
  direction: both
- topic: /sjtu_drone/cmd_vel
  type: geometry_msgs/msg/Twist
  direction: both
- topic: /sjtu_drone/odom
  type: nav_msgs/msg/Odometry
  direction: both
- topic: /sjtu_drone/imu
  type: sensor_msgs/msg/Imu
  direction: both
- topic: /sjtu_drone/pose
  type: geometry_msgs/msg/Pose
  direction: both
- topic: /sjtu_drone/camera_front
  type: sensor_msgs/msg/Image
  direction: both
- topic: /sjtu_drone/camera_front_info
  type: sensor_msgs/msg/CameraInfo
  direction: both
- topic: /sjtu_drone/camera_bottom
  type: sensor_msgs/msg/Image
  direction: both
- topic: /sjtu_drone/camera_bottom_info
  type: sensor_msgs/msg/CameraInfo
  direction: both
- topic: /sjtu_drone/sonar
  type: sensor_msgs/msg/Range
  direction: both
- topic: /sjtu_drone/laserscan
  type: sensor_msgs/msg/LaserScan
  direction: both
- topic: /sjtu_drone/gps/data
  type: sensor_msgs/msg/NavSatFix
  direction: both
