# Pose (used by pose_to_tf to publish world -> husky/base_link)
- ros_topic_name: '/husky/pose'
  gz_topic_name: '/model/husky/pose'
  ros_type_name: 'geometry_msgs/msg/PoseArray'
  gz_type_name: 'gz.msgs.Pose_V'
  direction: GZ_TO_ROS

# Position of joints - published to /husky/joint_states (not shared with other robots)
- ros_topic_name: '/husky/joint_states'
  gz_topic_name: '/model/husky/joint_states'
  ros_type_name: 'sensor_msgs/msg/JointState'
  gz_type_name: 'ignition.msgs.Model'
  direction: GZ_TO_ROS

# Odometry
- ros_topic_name: '/husky/odom'
  gz_topic_name: '/model/husky/odometry'
  ros_type_name: 'nav_msgs/msg/Odometry'
  gz_type_name: 'ignition.msgs.Odometry'
  direction: GZ_TO_ROS

# Inertial Measurement Unit
- ros_topic_name: '/husky/imu'
  gz_topic_name: '/model/husky/imu'
  ros_type_name: 'sensor_msgs/msg/Imu'
  gz_type_name: 'ignition.msgs.IMU'
  direction: GZ_TO_ROS

# Command velocity
- ros_topic_name: '/husky/cmd_vel'
  gz_topic_name: '/model/husky/cmd_vel'
  ros_type_name: 'geometry_msgs/msg/Twist'
  gz_type_name: 'ignition.msgs.Twist'
  direction: ROS_TO_GZ

# Lidar: laserscan
- ros_topic_name: "/husky/laserscan"
  gz_topic_name: "/model/husky/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

# Camera: RGB
- ros_topic_name: "/husky/camera/image"
  gz_topic_name: "/model/husky/camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS

# Sonar
- ros_topic_name: "/husky/sonar"
  gz_topic_name: "/model/husky/sonar"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS
